### ISSUE TITLE
Yarn incompatible with this module

### ISSUE THREAD

**Issue by rin3s** [chrisblossom/clean-self-webpack-plugin#1]
Hello,

We're having issues with the latest version `2.0.2`.
When Jenkins attempts to install, we get the following:

```
Now using node v8.1.2 (npm v5.0.3)
yarn install v0.24.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error clean-self-webpack-plugin@2.0.2: The engine "yarn" is incompatible with this module. Expected version ">=1.6.0".
error Found incompatible module
```

The previous version `2.0.1` works fine, as well as just running `2.0.2` on a local node server.

**Comment by chrisblossom** [comment]
Thanks for the report! Please try `2.0.3` and let me know if that fixes your issue.

https://github.com/chrisblossom/clean-self-webpack-plugin/commit/53ed63b4ce125d6e3100bde4d79951785435036a

**Comment by rin3s** [comment]
Yes, this fixed our issue and Jenkins will build again.
Thanks! 👍

**Comment by rin3s** [comment]
Fair point, thanks. Will forward and get it updated. 😃
